home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name='home'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^about/$', views.about, name='about'),
]

list/urls.py
from django.conf.urls import url
from . import views

app_name = 'lists'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<list_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<list_id>[0-9]+)/add_item/$', views.add_item, name='add_item'),
	url(r'^(?P<list_id>[0-9]+)/members/$', views.members, name='members'),
	url(r'^(?P<list_id>[0-9]+)/find_member/$', views.find_member, name='find_member'),
	url(r'^(?P<list_id>[0-9]+)/add_member/$', views.add_member, name='add_member'),
	url(r'^(?P<list_id>[0-9]+)/remove_member/$', views.remove_member, name='remove_member'),
	url(r'^(?P<list_id>[0-9]+)/leave_list/$', views.leave_list, name='leave_list'),
	url(r'^(?P<list_id>[0-9]+)/edit$', views.edit, name='edit'),
	url(r'^(?P<list_id>[0-9]+)/destroy$', views.destroy, name='destroy'),
]

profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'
urlpatterns = [
	url(r'^(?P<profile_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<profile_id>[0-9]+)/edit$', views.edit, name='edit'),
]

list/models.py
from django.db import models
from django.utils import timezone


class List(models.Model):
	title = models.CharField(max_length=50)
	creator = models.ForeignKey('auth.User', related_name='owned_lists')
	description = models.TextField(blank=True, max_length=300)
	members = models.ManyToManyField('auth.User', related_name='lists')
	private = models.BooleanField(default=True)
	deleted = models.BooleanField(default=False)
	created_at = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title


	def update_item_status(self, item, change):
		if item[1] == True:
			self.items.add(item[0])
			change.old_status = 4
		else:
			last_change = item[0].newest_change()
			last_change.not_newest_change()
			last_change.save()
			change.old_status = last_change.current_status
		return [item[0], change]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.core.exceptions import ValidationError
from datetime import date


def AgeValidator(value):
	today = date.today()
	age = today.year - value.year - ((today.month, today.day) < (value.month, value.day))
	if age < 18:
		raise ValidationError('You must be at least 18 years old to register.')


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.TextField(max_length=300, blank=True)
	birth_date = models.DateField(null=False, validators=[AgeValidator], default=date.today)

	def __unicode__(self):
		return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

list/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import List
from items.models import Item, Change
from django.contrib.auth.models import User
from todolists.core.forms import NewKitchenForm, KitchenEditForm, ItemForm


def index(request):
	user = request.user
	if user.is_authenticated() and request.method == "POST":
		form = NewKitchenForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			kitchen = List(**data)
			kitchen.creator = user
			kitchen.save()
			kitchen.members.add(user)
			return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id)))
		else:
			return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
	else:
		return HttpResponseRedirect(reverse('home:index'))


@login_required(redirect_field_name=None, login_url='/')
def detail(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	itemForm = ItemForm()
	if kitchen.deleted == False:
		if user in kitchen.members.all():
			if request.method == 'POST' and KitchenEditForm(request.POST).is_valid():
				kitchen.description = request.POST['description']
				kitchen.private = True if 'private' in request.POST else False
				kitchen.save()
				return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id, )))
			else:
				return render(request, 'lists/detail.html', { 'kitchen': kitchen, 'item_form': itemForm })
		elif kitchen.private == False:
			return render(request, 'lists/detail.html', { 'kitchen': kitchen })
		else:
			return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def add_item(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		item_name = request.POST['name'].strip().capitalize()
		item = kitchen.items.get_or_create(name=item_name)
		if item[1] == True:
			item[0].notes = request.POST['notes']
		change = Change(current_status=request.POST['status'], owner = request.user, item = item[0])
		item_and_change = kitchen.update_item_status(item, change)
		item_and_change[0].save()
		item_and_change[1].save()
		return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id,)))
	else:
		HttpResponseRedirect(reverse('profiles:detail', args=(request.user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def members(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if user in kitchen.members.all():
		return render(request, 'lists/members.html', { 'kitchen': kitchen })
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def find_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			query = request.POST['user-search'].strip()
			search_results = User.objects.filter(username__icontains=query)
			return render(request, 'lists/find_member.html', {'kitchen': kitchen, 'results': search_results})
		else:
			return render(request, 'lists/find_member.html', { 'kitchen': kitchen})
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def add_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			name = request.POST['username']
			new_member = get_object_or_404(User, username=name)
			if new_member not in kitchen.members.all():
				kitchen.members.add(new_member)
			return HttpResponseRedirect(reverse('lists:members', args=(kitchen.id,)))
		else:
			return HttpResponseRedirect(reverse('lists:find_member', args=(kitchen.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def remove_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			name = request.POST['username']
			member_to_remove = get_object_or_404(User, username=name)
			if member_to_remove in kitchen.members.all():
				kitchen.members.remove(member_to_remove)
		return HttpResponseRedirect(reverse('lists:members', args=(kitchen.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def leave_list(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if (kitchen.deleted == False and user in kitchen.members.all() and user != kitchen.creator):
		kitchen.members.remove(user)
	return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def edit(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user == kitchen.creator:
		kitchenForm = KitchenEditForm(instance=kitchen)
		return render(request, 'lists/edit.html', {'kitchen': kitchen, 'form': kitchenForm})
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def destroy(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user == kitchen.creator:
		kitchen.deleted = True
		kitchen.save()
	return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))

profiles/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import update_session_auth_hash, authenticate
from todolists.core.forms import UserUpdateEmailForm, UserUpdatePasswordForm, UserUpdateBioForm, UserUpdateNameForm, NewKitchenForm
from .models import Profile
from list.models import List


@login_required(redirect_field_name=None, login_url='/')
def detail(request, profile_id):
	profile = get_object_or_404(Profile, pk=profile_id)
	user = request.user
	if request.method == 'POST' and user.profile.id == int(profile_id):
		data = request.POST
		if 'first_name' in data:
			user.first_name = data['first_name']
			user.last_name = data['last_name']
		elif 'email' in data:
			user.email = data['email']
		elif 'current_password' in data and authenticate(username=user.username, password=data['current_password']) == user:
			if data['password1'] == data['password2']:
				user.set_password(data['password1'])
				update_session_auth_hash(request, user)
		elif 'bio' in data:
			user.profile.bio = data['bio']
		user.save()
		return HttpResponseRedirect(reverse('profiles:detail', args=(profile.id,)))
	elif user.profile.id == int(profile_id):
		new_kitchen_form = NewKitchenForm()
		return render(request, 'profiles/detail.html', {'profile': profile, 'kitchen_form': new_kitchen_form, })
	else:
		return render(request, 'profiles/detail.html', {'profile': profile, 'user': user, })


@login_required(redirect_field_name=None, login_url='/')
def edit(request, profile_id):
	user = request.user
	profile = get_object_or_404(Profile, pk=user.profile.id)
	if user.profile.id == int(profile_id):
		nameForm = UserUpdateNameForm(instance=request.user)
		bioForm = UserUpdateBioForm(instance=profile)
		emailForm = UserUpdateEmailForm(instance=request.user)
		passwordForm = UserUpdatePasswordForm()
		newKitchenForm = NewKitchenForm()
		return render(request, 'profiles/editprof.html',{'profile': profile, 'name_form': nameForm, 'bio_form': bioForm, 'email_form': emailForm, 'password_form': passwordForm, 'kitchen_form': newKitchenForm })
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(profile.id,)))

list/templates/profiles/detail.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}{{ profile.user.username }}{% endblock %}

{% block topblock %}
<div class="top-block-left">
{% if kitchen_form %}
	<a href="{% url 'profiles:edit' profile.id %}" class="edit-profile" title="Edit Profile">
		<img src="{% static 'editProfileGreen.png' %}" />
		<p>Edit</p>
	</a>
	<a href="#" class="open-kitchen-form" title="Add Kitchen">
		<img src="{% static 'AddKitchenGreen.png' %}" />
		<p>Kitchen</p>
	</a>
</div>
<div class="top-block-right">
	<h1>{{ profile.user.username }}</h1>
{% elif user %}
	<a href="{% url 'profiles:detail' user.profile.id %}" title="My Profile" >
		<img src="{% static 'viewUserGreen.png' %}" />
		<p>Profile</p>
	</a>
</div>
<div class="top-block-right">
	<h1><span>welcome to</span>{{ profile.user.username }}<span>'s profile</span></h1>
{% endif %}
</div>
{% endblock %}

{% block content %}
<div class="page">

<p>{{ profile.bio }}</p>
<ul class="blocklist">

{% if user != profile.user %}
	<h3>Kitchens</h3>
	{% for list in profile.user.lists.all %}
		<li>
		{% if list.private == False or user in list.members.all %}
			<a class="text" href="{% url 'lists:detail' list.id %}">{{ list.title }}</a>
			<div class="icon-links">
			{% if list.private == True %}
				<span class='icon-box' title='Private'><p class='icon'>P</p></span>
			{% endif %}
			<!-- Is profile person creator or member? -->
			{% if profile.user == list.creator %}
				<span class='icon-box'  title='Member'><img class='icon' src="{% static 'viewUserGreen.png' %}" /></span>
			{% else %}
				<span class='icon-box'  title='Member'><img class='icon' src="{% static 'viewUserBlue.png' %}" /></span>
			{% endif %}
			</div>
			<!-- Indicate if I am member or creator -->
			{% if user == list.creator %}
				<span class='owner-icon' title='Created by you'><img class='icon' src="{% static 'viewUserGreen.png' %}" /></span>
			{% elif user in list.members.all %}
				<span class='owner-icon' title='You are a member'><img class='icon' src="{% static 'viewUserBlue.png' %}" /></span>
			{% endif %}
		{% else %}
			<p class="text" >{{ list.title }}</p>
			<div class="icon-links">
				<span class='icon-box' title='Private'><p class='icon'>P</p></span>
				{% if profile.user.id == list.creator.id %}
					<span class="icon-box" title="Owner"><img class='icon' src="{% static 'viewUserGreen.png' %}" /></span>
				{% else %}
					<span class="icon-box" title="Member"><img class='icon' src="{% static 'viewUserBlue.png' %}" /></span>
				{% endif %}
			</div>
		{% endif %}
		</li>
	{% endfor %}

{% elif profile %}
		
	<h3>Your Kitchens</h3>
	<a class="filter-link all" href="#view-all">View All</a>
	<a class="filter-link active" href="#view-active">Active</a>

	{% for list in profile.user.lists.all %}
		{% if list.deleted == True %}
		<li class="deleted">
			<p class="text">{{ list.title }}</p>
			<div class='icon-links'>
				<span class='icon-box'><p class=''>Deleted</p></span>
			</div>
			{% if profile.user == list.creator %}
				<span class="owner-icon" title="Owner"><img class='icon' src="{% static 'viewUserGreen.png' %}" /></span>
			{% else %}
				<span class="owner-icon" title="Member"><img class='icon' src="{% static 'viewUserBlue.png' %}" /></span>
			{% endif %}
		</li>
		{% else %}
		<li>
			<a class="text" href="{% url 'lists:detail' list.id %}">{{ list.title }}</a>
			<div class="icon-links">
				{% if profile.user == list.creator %}
					<form class="icon-box click delete-kitchen" action="{% url 'lists:destroy' list.id %}" method="post" title="Delete">
					{% csrf_token %}
						<input class="icon" type="image" src="{% static 'deleteBlue.png' %}" />
					</form>
					<a class="icon-box click" title="Edit" href="{% url 'lists:edit' list.id %}" ><img class="icon" src="{% static 'editBlue.png' %}" /></a>
				{% else %}
					<form class="icon-box click" action="{% url 'lists:leave_list' list.id %}" method="post" title="Leave">
						{% csrf_token %}
						<input class="icon" type="image" src="{% static 'leaveBlue.png' %}" />
					</form>
				{% endif %}
			</div>
			{% if profile.user == list.creator %}
				<span class="owner-icon" title="Owner"><img class='icon' src="{% static 'viewUserGreen.png' %}" /></span>
			{% else %}
				<span class="owner-icon" title="Member"><img class='icon' src="{% static 'viewUserBlue.png' %}" /></span>
			{% endif %}
		</li>
		{% endif %}
	{% endfor %}
{% endif %}

</ul>
</div>

{% if profile.user == user %}
	{% include "lists/new_kitchen_form.html" with kitchen_form=kitchen_form %}
{% endif %}

{% endblock %}

list/templates/profiles/editprof.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}{{ profile.user.username }}{% endblock %}

{% block topblock %}
{% if profile %}
<div class="top-block-left">
	<a href="{% url 'profiles:detail' profile.id %}" class="edit-profile" title="Profile">
		<img src="{% static 'viewUserGreen.png' %}" />
		<p>Profile</p>
	</a>
</div>
<div class="top-block-right">
	<h1><span>Edit</span> {{ profile.user.username }}</h1>
</div>

{% endif %}
{% endblock %}

{% block content %}

<div class="edit-user page">
	{% if user.is_authenticated %}
		<ul class="blocklist edit-list">
			<li><a href="#name">Update Name</a></li>
			<li><a href="#bio">Edit Bio</a></li>
			<li><a href="#email">Change Email</a></li>
			<li><a href="#password">Update Password</a></li>
		</ul>

	<div class="edit-main">
		<div class="current-info selected">
			<p>Select Item to update or return to your <a href="{% url 'profiles:detail' profile.id %}" >profile</a>.</p>
		</div>

		<div class="current-info" id="bio">
			<form action="{% url 'profiles:detail' profile.id %}" method="post" class="edit-form user-form">
				<h4>Edit Bio</h4>
				{% csrf_token %}
				{{ bio_form.as_p }}
				<input type="submit" value="Update" />
			</form>
		</div>

		<div class="current-info" id="name">
			<form action="{% url 'profiles:detail' profile.id %}" method="post" class="edit-form user-form">
				<h4>Update Name</h4>
				{% csrf_token %}
				{{ name_form.as_p }}
				<input type="submit" value="Update" />
			</form>
		</div>

		<div class="current-info" id="password">
			<form action="{% url 'profiles:detail' profile.id %}" method="post" class="edit-form user-form" >
				<h4>Update Password</h4>
				{% csrf_token %}
				{{ password_form.as_p }}
				<input type="submit" value="Update" />
			</form>
		</div>
		
		<div class="current-info" id="email">
			<form action="{% url 'profiles:detail' profile.id %}" method="post" class="edit-form user-form" >
				<h4>Update Email</h4>
				{{ email_form.as_p }}
				<input type="submit" value="Update" />
			</form>
		</div>
	</div>
	{% endif %}
</div>

{% endblock %}