home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name='home'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^about/$', views.about, name='about'),
]

list/urls.py
from django.conf.urls import url
from . import views

app_name = 'lists'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<list_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<list_id>[0-9]+)/add_item/$', views.add_item, name='add_item'),
	url(r'^(?P<list_id>[0-9]+)/members/$', views.members, name='members'),
	url(r'^(?P<list_id>[0-9]+)/find_member/$', views.find_member, name='find_member'),
	url(r'^(?P<list_id>[0-9]+)/add_member/$', views.add_member, name='add_member'),
	url(r'^(?P<list_id>[0-9]+)/remove_member/$', views.remove_member, name='remove_member'),
	url(r'^(?P<list_id>[0-9]+)/leave_list/$', views.leave_list, name='leave_list'),
	url(r'^(?P<list_id>[0-9]+)/edit$', views.edit, name='edit'),
	url(r'^(?P<list_id>[0-9]+)/destroy$', views.destroy, name='destroy'),
]

profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'
urlpatterns = [
	url(r'^(?P<profile_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<profile_id>[0-9]+)/edit$', views.edit, name='edit'),
]

home/models.py
from django.db import models

# Create your models here.

list/models.py
from django.db import models
from django.utils import timezone


class List(models.Model):
	title = models.CharField(max_length=50)
	creator = models.ForeignKey('auth.User', related_name='owned_lists')
	description = models.TextField(blank=True, max_length=300)
	members = models.ManyToManyField('auth.User', related_name='lists')
	private = models.BooleanField(default=True)
	deleted = models.BooleanField(default=False)
	created_at = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title


	def update_item_status(self, item, change):
		if item[1] == True:
			self.items.add(item[0])
			change.old_status = 4
		else:
			last_change = item[0].newest_change()
			last_change.not_newest_change()
			last_change.save()
			change.old_status = last_change.current_status
		return [item[0], change]

home/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.contrib.auth.models import User
from todolists.core.forms import UserRegistrationForm, UserLoginForm, NewKitchenForm
from list.models import List


def index(request):
  kitchens = List.objects.filter(private=False, deleted=False)
  if request.user.is_authenticated():
    user = request.user
    newKitchenForm = NewKitchenForm()
  else:
    user = None
    newKitchenForm = None
  return render(request, 'home/index.html', { 'user': user, 'kitchens': kitchens, 'kitchen_form': newKitchenForm })


def register(request):
  registration_form = UserRegistrationForm()
  if request.method == 'POST':
    form = UserRegistrationForm(request.POST)
    if form.is_valid():
      user = form.save()
      user.refresh_from_db()
      user.profile.birth_date = form.cleaned_data.get('birth_date')
      user.profile.bio = form.cleaned_data.get('bio')
      user.save()
      raw_password = form.cleaned_data.get('password1')
      user = authenticate(username=user.username, password=raw_password)
      user_login(request, user)
      return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
    else:
      return render(request, 'home/register.html', {'registration_form': form })
  elif request.is_ajax():
    register = render_to_string('home/register_form.html', {'register_form': registration_form}, request=request)
    return JsonResponse(login, safe=False)
  else:
    return render(request, 'home/register.html', { 'registration_form': registration_form })


def login(request):
  login_form = UserLoginForm()
  if request.method == "POST":
    form = UserLoginForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(username=username, password=password)
      if user is not None:
        user_login(request, user)
        return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
      else:
        return render(request, 'home/login.html', { 'login_form': form })
    else:
      return render(request, 'home/login.html', { 'login_form': form })
  elif request.is_ajax():
    login = render_to_string('home/login_form.html', {'login_form': login_form }, request=request)
    return JsonResponse(login, safe=False)
  else:
    return render(request, 'home/login.html', {'login_form': login_form })


def logout(request):
  user_logout(request)
  return HttpResponseRedirect(reverse('home:index'))


def about(request):
  return render(request, 'home/about.html')

list/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import List
from items.models import Item, Change
from django.contrib.auth.models import User
from todolists.core.forms import NewKitchenForm, KitchenEditForm, ItemForm


def index(request):
	user = request.user
	if user.is_authenticated() and request.method == "POST":
		form = NewKitchenForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			kitchen = List(**data)
			kitchen.creator = user
			kitchen.save()
			kitchen.members.add(user)
			return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id)))
		else:
			return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
	else:
		return HttpResponseRedirect(reverse('home:index'))


@login_required(redirect_field_name=None, login_url='/')
def detail(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	itemForm = ItemForm()
	if kitchen.deleted == False:
		if user in kitchen.members.all():
			if request.method == 'POST' and KitchenEditForm(request.POST).is_valid():
				kitchen.description = request.POST['description']
				kitchen.private = True if 'private' in request.POST else False
				kitchen.save()
				return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id, )))
			else:
				return render(request, 'lists/detail.html', { 'kitchen': kitchen, 'item_form': itemForm })
		elif kitchen.private == False:
			return render(request, 'lists/detail.html', { 'kitchen': kitchen })
		else:
			return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def add_item(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		item_name = request.POST['name'].strip().capitalize()
		item = kitchen.items.get_or_create(name=item_name)
		if item[1] == True:
			item[0].notes = request.POST['notes']
		change = Change(current_status=request.POST['status'], owner = request.user, item = item[0])
		item_and_change = kitchen.update_item_status(item, change)
		item_and_change[0].save()
		item_and_change[1].save()
		return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id,)))
	else:
		HttpResponseRedirect(reverse('profiles:detail', args=(request.user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def members(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if user in kitchen.members.all():
		return render(request, 'lists/members.html', { 'kitchen': kitchen })
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def find_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			query = request.POST['user-search'].strip()
			search_results = User.objects.filter(username__icontains=query)
			return render(request, 'lists/find_member.html', {'kitchen': kitchen, 'results': search_results})
		else:
			return render(request, 'lists/find_member.html', { 'kitchen': kitchen})
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def add_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			name = request.POST['username']
			new_member = get_object_or_404(User, username=name)
			if new_member not in kitchen.members.all():
				kitchen.members.add(new_member)
			return HttpResponseRedirect(reverse('lists:members', args=(kitchen.id,)))
		else:
			return HttpResponseRedirect(reverse('lists:find_member', args=(kitchen.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def remove_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			name = request.POST['username']
			member_to_remove = get_object_or_404(User, username=name)
			if member_to_remove in kitchen.members.all():
				kitchen.members.remove(member_to_remove)
		return HttpResponseRedirect(reverse('lists:members', args=(kitchen.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def leave_list(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if (kitchen.deleted == False and user in kitchen.members.all() and user != kitchen.creator):
		kitchen.members.remove(user)
	return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def edit(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user == kitchen.creator:
		kitchenForm = KitchenEditForm(instance=kitchen)
		return render(request, 'lists/edit.html', {'kitchen': kitchen, 'form': kitchenForm})
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def destroy(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user == kitchen.creator:
		kitchen.deleted = True
		kitchen.save()
	return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))

list/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block topblock %}
<div class="top-block-left">
{% if user.is_authenticated %}
	<a href="{% url 'profiles:detail' user.profile.id %}" title="Profile">
		<img src="{% static 'viewUserGreen.png' %}" />
		<p>Profile</p>
	</a>
{% endif %}
</div>

<div class="top-block-right">
	<h1>About Us</h1>
</div>

{% endblock %}

{% block content %}
	<div class='page'>
	<h3>Mission</h3>
	<p>We are here to help organize your kitchen and make grocery shopping for people with a shared kitchen more convenient!</p>
	<p></p>
	</div>
{% endblock %}

list/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<html>
<head>
	{% load static %}
	<link rel="stylesheet" href="{% static 'home/newStyle.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.ui.touch-punch.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/app.js' %}"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>KITCHiN | {% block title %}Home{% endblock %}</title>
</head>

<body>
		<div class="page-overlay display-none"></div>
<div id="content">
	{% block header %}
		{% include "home/header.html" with user=user %}
	{% endblock %}

	<div id="main">
		<div class="general-modal display-none">
			<div class="modal-top-bar">
				<h5>Name</h5>
				<div class="modal-close-x hover-orange"><a href="#">x</a></div>
			</div>
			<div class="modal-main"></div>
		</div>

		<div class="top-block">
			{% block topblock %}
			{% endblock%}
		</div>

		{% block content %}
		{% endblock %}
	</div>
</div>

<footer><p>&copy; KitchenIn' 2017</p></footer>

</body>
</html>

list/templates/home/header.html
{% load static %}
<div class="header-bar">
	<img src="{% static 'kitcheninLogoNew.png' %}" class="header-bar-img" />
	<ul class='header-bar-menu'>
		<li class="nav-link">
			<a href="{% url 'home:index' %}">
			<img src="{% static 'homeInverted.png' %}" /><p>Home</p></a>
		</li>
		{% if user.is_authenticated %}
		<li class="nav-link">
			<a href="{% url 'profiles:detail' user.profile.id %}">
				<img src="{% static 'kitchenInverted.png' %}" /><p>Kitchens</p></a>
		</li>
		{% else %}
		<li class="nav-link">
			<a href="{% url 'home:login' %}">
				<img src="{% static 'loginInverted.png' %}" /><p>Login</p></a>
		</li>
		{% endif %}
		<li class="nav-link">
			<a href="{% url 'home:about' %}">
				<img src="{% static 'aboutInverted.png' %}" /><p>About Us</p></a>
		</li>
		{% if user.is_authenticated %}
		<li class="nav-link">
			<a href="{% url 'home:logout' %}">
				<img src="{% static 'logoutInverted.png' %}" /><p>Logout</p></a>
		</li>
		{% endif %}
	</ul>
</div>

list/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block topblock %}
{% if user.is_authenticated %}
<div class="top-block-left">
	<a href="{% url 'profiles:detail' user.profile.id %}" title="Profile">
		<img src="{% static 'viewUserGreen.png' %}" />
		<p>Profile</p>
	</a>
	<a href="#" class="open-kitchen-form open-form-link" title="Add Kitchen">
		<img src="{% static 'AddKitchenGreen.png' %}" />
		<p>Kitchen</p>
	</a>

</div>
<div class="top-block-right">
	<h1>{{ user.username }}</h1>
</div>

{% endif %}
{% endblock %}

{% block content %}
	<div class='page'>

	{% if user.is_authenticated %}
		<p>you are logged in as {{user.username}}</p>
		<a href="{% url 'profiles:detail' user.profile.id %}" >My Profile!</a>
	{% else %}
		<a href="{% url 'home:register' %}" class='register-link button-link'>Register</a>
		<a href="{% url 'home:login' %}" class='login-link button-link'>Login</a>
	{% endif %}

	{% if kitchens %}
		<ul class="blocklist">
			<h3>Public Kitchens</h3>
			{% for kitchen in kitchens.all %}
				<li><a class="text" href="{% url 'lists:detail' kitchen.id %}">{{ kitchen.title }}</a></li>
			{% endfor %}
		</ul>
	{% endif %}
	</div>

{% if kitchen_form %}
	{% include "lists/new_kitchen_form.html" with kitchen_form=kitchen_form %}
{% endif %}

{% endblock %}

list/templates/home/login.html
{% extends 'home/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="page">

{% if user.is_authenticated %}
	<p>you are logged in!</p>
	<a href="{% url 'profiles:detail' user.profile.id %}" >My Profile!</a>
{% else %}
<a href="{% url 'home:register' %}" class='Register-link open-form-link'>Register</a>

<form action="{% url 'home:login' %}" method="post" class="user-form">
<h3>Login</h3>
	{% csrf_token %}
	{{ login_form.as_p }}
	<input type="submit" value="Login" />
</form>

{% endif %}
</div>

{% endblock %}

list/templates/home/login_form.html
{% load static %}

<form action="{% url 'home:login' %}" method="post" class="user-form">
<h3>Login</h3>
	{% csrf_token %}
	{{ login_form.as_p }}
	<input type="submit" value="Login" />
</form>

list/templates/home/register.html
{% extends 'home/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class='page'>

{% if user.is_authenticated %}
	<p>you are logged in!</p>
	<a href="{% url 'profiles:detail' user.profile.id %}" >My Profile!</a>
{% else %}
<a href="{% url 'home:login' %}" class='login-link open-form-link'>Login</a>

<form action="{% url 'home:register' %}" method='post' class="user-form">
<h3>Register</h3>
	{% csrf_token %}
	{{ registration_form.as_p }}
	<input type="submit" value="Register" />
</form>

{% endif %}
</div>
{% endblock %}

list/templates/home/register_form.html
{% load static %}

<form action="{% url 'home:register' %}" method='post' class="user-form">
<h3>Register</h3>
	{% csrf_token %}
	{{ registration_form.as_p }}
	<input type="submit" value="Register" />
</form>