home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name='home'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^about/$', views.about, name='about'),
]

items/urls.py
from django.conf.urls import url
from . import views

app_name='items'
urlpatterns = [
	url(r'^(?P<item_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<item_id>[0-9]+)/move/$', views.move, name='move'),
]

list/urls.py
from django.conf.urls import url
from . import views

app_name = 'lists'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<list_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<list_id>[0-9]+)/add_item/$', views.add_item, name='add_item'),
	url(r'^(?P<list_id>[0-9]+)/members/$', views.members, name='members'),
	url(r'^(?P<list_id>[0-9]+)/find_member/$', views.find_member, name='find_member'),
	url(r'^(?P<list_id>[0-9]+)/add_member/$', views.add_member, name='add_member'),
	url(r'^(?P<list_id>[0-9]+)/remove_member/$', views.remove_member, name='remove_member'),
	url(r'^(?P<list_id>[0-9]+)/leave_list/$', views.leave_list, name='leave_list'),
	url(r'^(?P<list_id>[0-9]+)/edit$', views.edit, name='edit'),
	url(r'^(?P<list_id>[0-9]+)/destroy$', views.destroy, name='destroy'),
]

profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'
urlpatterns = [
	url(r'^(?P<profile_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<profile_id>[0-9]+)/edit$', views.edit, name='edit'),
]

list/models.py
from django.db import models
from django.utils import timezone


class List(models.Model):
	title = models.CharField(max_length=50)
	creator = models.ForeignKey('auth.User', related_name='owned_lists')
	description = models.TextField(blank=True, max_length=300)
	members = models.ManyToManyField('auth.User', related_name='lists')
	private = models.BooleanField(default=True)
	deleted = models.BooleanField(default=False)
	created_at = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title


	def update_item_status(self, item, change):
		if item[1] == True:
			self.items.add(item[0])
			change.old_status = 4
		else:
			last_change = item[0].newest_change()
			last_change.not_newest_change()
			last_change.save()
			change.old_status = last_change.current_status
		return [item[0], change]

list/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import List
from items.models import Item, Change
from django.contrib.auth.models import User
from todolists.core.forms import NewKitchenForm, KitchenEditForm, ItemForm


def index(request):
	user = request.user
	if user.is_authenticated() and request.method == "POST":
		form = NewKitchenForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			kitchen = List(**data)
			kitchen.creator = user
			kitchen.save()
			kitchen.members.add(user)
			return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id)))
		else:
			return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
	else:
		return HttpResponseRedirect(reverse('home:index'))


@login_required(redirect_field_name=None, login_url='/')
def detail(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	itemForm = ItemForm()
	if kitchen.deleted == False:
		if user in kitchen.members.all():
			if request.method == 'POST' and KitchenEditForm(request.POST).is_valid():
				kitchen.description = request.POST['description']
				kitchen.private = True if 'private' in request.POST else False
				kitchen.save()
				return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id, )))
			else:
				return render(request, 'lists/detail.html', { 'kitchen': kitchen, 'item_form': itemForm })
		elif kitchen.private == False:
			return render(request, 'lists/detail.html', { 'kitchen': kitchen })
		else:
			return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def add_item(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		item_name = request.POST['name'].strip().capitalize()
		item = kitchen.items.get_or_create(name=item_name)
		if item[1] == True:
			item[0].notes = request.POST['notes']
		change = Change(current_status=request.POST['status'], owner = request.user, item = item[0])
		item_and_change = kitchen.update_item_status(item, change)
		item_and_change[0].save()
		item_and_change[1].save()
		return HttpResponseRedirect(reverse('lists:detail', args=(kitchen.id,)))
	else:
		HttpResponseRedirect(reverse('profiles:detail', args=(request.user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def members(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if user in kitchen.members.all():
		return render(request, 'lists/members.html', { 'kitchen': kitchen })
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def find_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			query = request.POST['user-search'].strip()
			search_results = User.objects.filter(username__icontains=query)
			return render(request, 'lists/find_member.html', {'kitchen': kitchen, 'results': search_results})
		else:
			return render(request, 'lists/find_member.html', { 'kitchen': kitchen})
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def add_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			name = request.POST['username']
			new_member = get_object_or_404(User, username=name)
			if new_member not in kitchen.members.all():
				kitchen.members.add(new_member)
			return HttpResponseRedirect(reverse('lists:members', args=(kitchen.id,)))
		else:
			return HttpResponseRedirect(reverse('lists:find_member', args=(kitchen.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def remove_member(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user in kitchen.members.all():
		if request.method == "POST":
			name = request.POST['username']
			member_to_remove = get_object_or_404(User, username=name)
			if member_to_remove in kitchen.members.all():
				kitchen.members.remove(member_to_remove)
		return HttpResponseRedirect(reverse('lists:members', args=(kitchen.id,)))
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def leave_list(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if (kitchen.deleted == False and user in kitchen.members.all() and user != kitchen.creator):
		kitchen.members.remove(user)
	return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def edit(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user == kitchen.creator:
		kitchenForm = KitchenEditForm(instance=kitchen)
		return render(request, 'lists/edit.html', {'kitchen': kitchen, 'form': kitchenForm})
	else:
		return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))


@login_required(redirect_field_name=None, login_url='/')
def destroy(request, list_id):
	kitchen = get_object_or_404(List, pk=list_id)
	user = request.user
	if kitchen.deleted == False and user == kitchen.creator:
		kitchen.deleted = True
		kitchen.save()
	return HttpResponseRedirect(reverse('profiles:detail', args=(user.profile.id,)))

list/templates/lists/detail.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}{{ kitchen.title }}{% endblock %}

{% block topblock %}
{% if kitchen %}
<div class='top-block-left'>
	{% if user in kitchen.members.all %}
		<a href="#" class='add-item' title="Add Item">
			<img src="{% static 'addItemGreen.png' %}" />
			<p>Item</p>
		</a>
		<a href="{% url 'lists:edit' kitchen.id %}" class='member-page-link open-form-link' title="Edit">
			<img src="{% static 'editKitchenGreen.png' %}" />
			<p>Edit</p>
		</a>
	{% else %}
		<a href="{% url 'profiles:detail' user.profile.id %}" >
			<img src="{% static 'viewUserGreen.png' %}" />
			<p>Profile</p>
		</a>
	{% endif %}
</div>
<div class="top-block-right">
	<h1 class="kitchen-title">{{ kitchen.title }}</h1>
</div>
{% endif %}
{% endblock %}

{% block content %}

<p>{{ kitchen.description }}</p>

{% if kitchen %}

	{% if user in kitchen.members.all %}
		{% include "lists/member_detail.html" with kitchen=kitchen %}
	{% else %}
		{% include "lists/non_member_detail.html" with kitchen=kitchen %}
	{% endif %}


	{% if item_form %}
	<form action="{% url 'lists:add_item' kitchen.id %}" method="post" class='add-item-form display-none user-form'>
		<h4>New Item</h4>
		{% csrf_token %}
		{{ item_form.as_p }}
		<input type="submit" value="Add" class="hover-orange" />
		<a href="#" class="cancel-link">cancel</a>
	</form>
	{% endif %}

{% endif %}

{% endblock %}

list/templates/lists/edit.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}{{ kitchen.title }}{% endblock %}

{% block topblock %}
{% if kitchen %}
<div class="top-block-left">
	<a href="{% url 'lists:detail' kitchen.id %}" class="" title="Kitchen">
		<img src="{% static 'viewKitchenGreen.png' %}" />
		<p>Kitchen</p>
	</a>
	<a href="{% url 'lists:members' kitchen.id %}" class="" title="Members">
		<img src="{% static 'viewUserGreen.png' %}" />
		<p>Members</p>
	</a>
</div>
<div class="top-block-right">
	<h1><span>Edit</span> {{ kitchen.title }}</h1>
</div>

{% endif %}
{% endblock %}

{% block content %}

<div class="page edit">
	{% if user.is_authenticated %}
		<form action="{% url 'lists:detail' kitchen.id %}" method="post" class="user-form" >
			<h3>Edit Description</h3>
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Update" />
		</form>
		<div class='delete-icon-link'>
			<form class="icon-box delete-kitchen" action="{% url 'lists:destroy' kitchen.id %}" method="post" title="Delete">
				{% csrf_token %}
				<input class="icon" type="image" src="{% static 'deleteBlue.png' %}" />
			</form>
		</div>
	{% endif %}
</div>

{% endblock %}

list/templates/lists/find_member.html
{% extends 'home/base.html' %}
{% load static %}

{% block topblock %}
{% if kitchen %}
<div class="top-block-left">
	<a href="{% url 'lists:detail' kitchen.id %}" title="View Kitchen">
		<img src="{% static 'viewKitchenGreen.png' %}" />
		<p>Kitchen</p>
	</a>
	<a href="{% url 'lists:members' kitchen.id %}" title="View Members">
		<img src="{% static 'viewUserGreen.png' %}" />
		<p>Members</p>
	</a>
</div>
<div class="top-block-right">
	<h1><span>Add Members to </span>{{ kitchen.title }}</h1>
</div>
{% endif %}
{% endblock %}

{% block content %}
{% if kitchen %}
<div class="kitchen-members page">
	<h3>User Search</h3>

	<form action="{% url 'lists:find_member' kitchen.id %}" method="post" class="user-form">
		{% csrf_token %}
		<p>
			<label>search:</label>
			<input type="text" name="user-search" placeholder="Enter Username" />
		</p>
		<input type="submit" value="search" />
	</form>

	{% if results %}
		<h5>Users Found</h5>
		<ul class="blocklist">
			{% for user in results.all %}
				<li><a class="text" href="{% url 'profiles:detail' user.profile.id %}">{{ user.username }}</a>
					<div class="icon-links">
						{% if user == kitchen.creator %}
							<span class="icon-box"><img class="icon" src="{% static 'viewUserGreen.png' %}" title="Owner" /></span>
						{% elif user in kitchen.members.all %}
							<span class="icon-box"><img class="icon" src="{% static 'viewUserBlue.png' %}" title="Member" /></span>
						{% else %}
							<form class="icon-box click" action="{% url 'lists:add_member' kitchen.id %}" method="post">
								{% csrf_token %}
								<input type="hidden" value="{{user.username}}" name="username">
								<input type="image" class="icon" src="{% static 'addUserBlue.png' %}" alt="Add!" title="Add" />
							</form>
						{% endif %}
					</div>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<h5>No Results. Search Above.</h5>
	{% endif %}

</div>
{% endif %}
{% endblock %}

list/templates/lists/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block topblock %}

<div class="top-block-left">
	<a href="#" class="open-kitchen-form open-form-link" title="Add Kitchen">
		<img src="{% static 'AddKitchen.png' %}" />
		<p>Kitchen</p>
	</a>
</div>
<div class="top-block-right">
	<h1>{{ user.username }}</h1>
</div>

{% endblock %}

{% block content %}
<div class="kitchen-members page">
<h3>Your Kitchens</h3>

<ul class="user-kitchen-list">
	{% if kitchens %}
	{% for kitchen in kitchens.all %}
		<li><a href="{% url 'lists:detail' kitchen.id %}">{{ kitchen.title }}</a>
		</li>
	{% endfor %}
	{% endif %}
</ul>
</div>

<form action="{% url 'lists:create' %}" method="post" class="new-kitchen-form display-none">
	{% csrf_token %}
	<div>
		<label>Name:</label>
		<input type="text" name="list-title" placeholder="Name" />
	</div>
	<div>
		<label>Description:</label>
		<textarea name="list-description" placeholder="Description"></textarea>
	</div>
	<input type="submit" value="create" />
	<a href="#" class="cancel-link">cancel</a>
</form>
{% endblock %}

list/templates/lists/kitchen_list.html
{% load static %}
<li class="list-item status-{{status}}" id="list-item-{{item.id}}" title="{{item.name}}">
	{{ item.name }}
	<div class="list-forms">
	{% if item.status != 1 %}
	<form action="{% url 'items:move' item.id %}" method="post" title="list" class="need-form ">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'listBlue.png' %}" value="1" alt="need" name="item-status" />
	</form>
	{% endif %}
	{% if item.status != 2 %}
	<form action="{% url 'items:move' item.id %}" method="post" title="pantry" class="pantry-form ">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'pantryBlue.png' %}" value="2" alt="pantry" name="item-status" />
	</form>
	{% endif %}
	{% if item.status != 3 %}
	<form action="{% url 'items:move' item.id %}" method="post" title="fridge" class="fridge-form ">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'fridgeBlue.png' %}" value="3" alt="fridge" name="item-status" />
	</form>
	{% endif %}
	<form action="{% url 'items:detail' item.id %}" method="get" title="edit" class="edit-form ">
		{% csrf_token %}
		<input class="edit-item-icon" type="image" src="{% static 'editBlue.png' %}" alt="edit" />
	</form>
	<form action="{% url 'items:move' item.id %}" method="post" title="remove" class="remove-form ">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'deleteBlue.png' %}" value="4" alt="fridge" name="item-status" />
	</form>
	</div>
</li>

list/templates/lists/main_kitchen_list.html
{% load static %}
<li>
	<a href="{% url 'items:detail' item.id %}" class='list-item'>{{ item.name }}</a>
	{% if item.status != 1 %}
	<form action="{% url 'items:move' item.id %}" method="post" title="list">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'list_icon.png' %}" value="1" alt="need" name="item-status" />
	</form>
	{% endif %}
	{% if item.status != 2 %}
	<form action="{% url 'items:move' item.id %}" method="post" title="pantry">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'pantry_icon.jpg' %}" value="2" alt="pantry" name="item-status" />
	</form>
	{% endif %}
	{% if item.status != 3 %}
	<form action="{% url 'items:move' item.id %}" method="post" title="fridge">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'fridge_icon.png' %}" value="3" alt="fridge" name="item-status" />
	</form>
	{% endif %}
	<form action="{% url 'items:move' item.id %}" method="post" title="remove">
		{% csrf_token %}
		<input class="move-item-icon" type="image" src="{% static 'delete_icon.png' %}" value="4" alt="fridge" name="item-status" />
	</form>
	<p>{{ item.notes }}</p>
</li>

list/templates/lists/member_detail.html
{% load static %}

<div class="kitchen-lists">
	<div class='kitchen-list kitchen-list-1'>
		<ul id="1-need">
		<h6><a href="#">NEED</a></h6>
			{% for item in kitchen.items.all %}
				{% if item.status == 1 %}
					{% include "lists/kitchen_list.html" with status=1 %}
				{% endif %}
			{% endfor %}
		</ul>
	</div>
	<div class="kitchen-list kitchen-list-2">
		<ul id="2-pantry">
		<h6><a href="#">PANTRY</a></h6>
			{% for item in kitchen.items.all %}
				{% if item.status == 2 %}
					{% include "lists/kitchen_list.html" with status=2 %}
				{% endif %}
			{% endfor %}
		</ul>
	</div>
	<div class="kitchen-list kitchen-list-3">
		<ul id="3-fridge">
		<h6><a href="#">FRIDGE</a></h6>
			{% for item in kitchen.items.all %}
				{% if item.status == 3 %}
					{% include "lists/kitchen_list.html" with status=3 %}
				{% endif %}
			{% endfor %}
		</ul>
	</div>
</div>

list/templates/lists/members.html
{% extends 'home/base.html' %}
{% load static %}

{% block topblock %}
{% if kitchen %}
<div class="top-block-left">
	<a href="{% url 'lists:detail' kitchen.id %}" title="View Kitchen">
		<img src="{% static 'viewKitchenGreen.png' %}" />
		<p>Kitchen</p>
	</a>
	<a href="{% url 'lists:find_member' kitchen.id %}" title="Add User">
		<img src="{% static 'findUserGreen.png' %}" />
		<p>Find</p>
	</a>
</div>
<div class="top-block-right">
	<h1>{{ kitchen.title }}</h1>
</div>
{% endif %}
{% endblock %}

{% block content %}
{% if kitchen %}
<div class="page kitchen-members">
<h3>Members</h3>

<h6>Owner: {{ kitchen.creator }}</h6>
<ul class="blocklist">
	{% for member in kitchen.members.all %}
		<li><a class="text" href="{% url 'profiles:detail' member.profile.id %}">{{ member.username }}</a>
			<div class="icon-links">
			{% if member == kitchen.creator %}
				<span class="icon-box"><img class="icon" src="{% static 'viewUserGreen.png' %}" title="Owner" /></span>
			{% else %}
				<form class="icon-box click" action="{% url 'lists:remove_member' kitchen.id %}" method="post" title="Remove" >
					{% csrf_token %}
					<input type="hidden" value="{{member.username}}" name="username">
					<input class="icon" type="image" src="{% static 'removeUserBlue.png' %}" alt="Remove" />
				</form>
			{% endif %}
			</div>
			{% if member == kitchen.creator %}
				<span class="owner-icon" title="Owner"><img class='icon' src="{% static 'viewUserGreen.png' %}" /></span>
			{% else %}
				<span class="owner-icon" title="Member"><img class='icon' src="{% static 'viewUserBlue.png' %}" /></span>
			{% endif %}
		</li>
	{% endfor %}
</ul>
</div>

{% endif %}
{% endblock %}

list/templates/lists/new_kitchen_form.html
{% load static %}

<form action="{% url 'lists:index' %}" method="post" class="new-kitchen-form display-none user-form">
	{% csrf_token %}
	{{ kitchen_form.as_p }}
	<input type="submit" value="create" />
	<a href="#" class="cancel-link">cancel</a>
</form>

list/templates/lists/non_member_detail.html
{% load static %}

<div class="kitchen-lists">
	<div class='public-list'>
		<ul>
		<h6>NEED</h6>
			{% for item in kitchen.items.all %}
				{% if item.status == 1 %}
					<li class='public-item'><p>{{item.name}}</p></li>
				{% endif %}
			{% endfor %}
		</ul>
	</div>
	<div class="public-list">
		<ul>
		<h6>PANTRY</h6>
			{% for item in kitchen.items.all %}
				{% if item.status == 2 %}
					<li class='public-item'><p>{{item.name}}</p></li>
				{% endif %}
			{% endfor %}
		</ul>
	</div>
	<div class="public-list">
		<ul>
		<h6>FRIDGE</h6>
			{% for item in kitchen.items.all %}
				{% if item.status == 3 %}
					<li class='public-item'><p>{{item.name}}</p></li>
				{% endif %}
			{% endfor %}
		</ul>
	</div>
</div>